services:
  postgres:
    image: postgres
    container_name: MP2I_PostgreSQL
    environment:
      - POSTGRES_DB=MP2I
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "2345:5432"

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - postgres

  bot:
    container_name: MP2I_Bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/MP2I/logs
    env_file:
      - .env
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql+psycopg2://root:root@postgres:5432/MP2I
    depends_on:
      - postgres
