version = 1

[formatters]
    [formatters.simple]
    format = "%(levelname)s: %(name)s - %(asctime)s -> %(message)s"
    datefmt = "%H:%M:%S"

    [formatters.verbose]
    format = "%(levelname)s: %(name)s - %(asctime)s -> %(message)s"
    datefmt = "%d/%m/%Y (%H:%M:%S)"

[handlers]
    [handlers.console]
    class = "logging.StreamHandler"
    formatter = "simple"
    level = "INFO"
    stream = "ext://sys.stdout"

    [handlers.file]
    class = "logging.handlers.RotatingFileHandler"
    formatter = "verbose"
    level = "DEBUG"
    filename = "./logs/bot.log"
    maxBytes = 100_000  # 100KB
    backupCount = 3

    [handlers.discord]
    class = "logging.handlers.RotatingFileHandler"
    formatter = "verbose"
    level = "DEBUG"
    filename = "./logs/discord.log"
    maxBytes = 200_000  # 200KB
    backupCount = 3

[loggers]
    [loggers.root]  # The default logger used for production
    level = "WARNING"
    handlers = ["console"]

    [loggers.discord]  # The logger used by Discord
    level = "INFO"
    handlers = ["discord"]
    propagate = 0  # No propagation to the root logger

    [loggers.development]
    level = "DEBUG"
    handlers = ["console", "file"]